// React/Integrating the Dashboard Viewer into an Application (TypeScript)/src/App.tsx
import React from 'react';
import { Stimulsoft } from 'stimulsoft-dashboards-js/Scripts/stimulsoft.viewer'
import './App.css';

class App extends React.Component {
    private viewer = new Stimulsoft.Viewer.StiViewer(undefined, 'StiViewer', false);
    private report = Stimulsoft.Report.StiReport.createNewDashboard();

    render() {
        return (
            <div id="viewer" className="App">
            </div>
        );
    }

    async componentDidMount() {
        console.log('Loading Viewer view');

        const response = await fetch('dashboard/DashboardChristmas.mrt');
        const data = await response.json();
        console.log('Load dashboard from url');
        this.report.loadDocument(data);
        this.viewer.report = this.report;

        console.log('Rendering the viewer to selected element');
        this.viewer.renderHtml('viewer');
    }

}

export default App;

// Angular/02. Working with dashboard viewer/src/app/app.component.ts
import { Component } from '@angular/core';
import { ViewEncapsulation } from '@angular/core';
import { Http } from '@angular/http';
import { Response } from '@angular/http';
import { Stimulsoft } from 'stimulsoft-dashboards-js/Scripts/stimulsoft.designer'

@Component({
  selector: 'app-root',
  template: `<div>
                  <h2>Stimulsoft Dashboards.JS Viewer</h2>
                  <div id="viewer"></div>
              </div>`,
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {
  viewer: any = new Stimulsoft.Viewer.StiViewer(null, 'StiViewer', false);
  report: any = Stimulsoft.Report.StiReport.createNewDashboard();

  ngOnInit() {
    console.log('Loading Viewer view');

    this.http.request('dashboard/DashboardChristmas.mrt').subscribe((data: Response) => {

      console.log('Load dashboard from url');
      this.report.loadDocument(data.json());
      this.viewer.report = this.report;

      console.log('Rendering the viewer to selected element');
      this.viewer.renderHtml('viewer');
    });
  }

  constructor(private http: Http) {

  }
}
